# ---------------------------------------------------------------
# MAIN SETTINGS
# ---------------------------------------------------------------

title: CariDiScho
subtitle: 2024
author:
  name: Alex Gil
  email: alex.gil@yale.edu
description: A Directory of Caribbean Digital Scholarship.
baseurl: "/caridischo"
year: "2024"

exclude:
  - Gemfile
  - Gemfile.lock
  - utilities
  - .gitignore
  - .git
  - .DS_Store
  - README.md
  - LICENSE.txt
  - Rakefile

# ---------------------------------------------------------------
# COLLECTION SETTINGS
# ---------------------------------------------------------------

collections:
  exhibits:
    output: true
  caridischo: # name of collection
    output: true # makes sure pages are output as html files
    layout: "caridischo_item" # the layout for the pages to use
    metadata:
      source: "caridischo.csv" # path to the metadata file within `_data`
    images:
      source: "raw_images/caridischo" # path to the directory of images within `_data`
  rip:
    output: true
    layout: "rip_item"
    metadata:
      source: "rip.csv"
    images:
      source: "raw_images/rip"

# --------------------------------------------------------------
# SEARCH INDEX SETTINGS
# --------------------------------------------------------------

search:
  main:
    index: "/search/index.json" # file the index will get written to
    collections:
      caridischo:
        content: true # whether or not to index page content
        fields: # the metadata fields to index
          - genre
          - label
          - claimed_genre
          - claimed_genre_en
          - claimed_genre_es
          - blurb_orig
          - blurb_en
          - blurb_es
          - creators
          - stewards

# --------------------------------------------------------------
# SITE MENU SETTINGS
# --------------------------------------------------------------

menu:
  - label: "Browse"
    link: "/collection/"
  - label: "Search"
    link: "/search/"
  - label: "About"
    link: "/about/"
    sub:
      - label: "Sources"
        link: "/sources/"
      - label: "FAQ"
        link: "/faq/"
      - label: "Credits"
        link: "/credits/"

# --------------------------------------------------------------
# POLYGLOT I18N LOCALIZATION
# https://github.com/untra/polyglot
# --------------------------------------------------------------
#

plugins:
  - jekyll-polyglot

languages: ["en", "es"]
default_lang: "en"
exclude_from_localization: ["img", "assets"]
parallel_localization: true

sass:
  sourcemap: never
